language: python

python:
  - "3.6"
  - "3.7"  # 3.7 development branch
  - "3.8"  # 3.7 development branch

install:
  - pip install pipenv
  - pipenv install --system

script:
  - python -m unittest
